from typing import Protocol, TypeVar

M = TypeVar("M")


class Repository(Protocol[M]):
    async def count(self, **filters) -> int: ...
    async def get_by_id(self, id) -> M | None: ...
    async def create(self, **kwargs) -> M: ...
    async def update(self, id, **kwargs) -> M | None: ...
    async def delete(self, id) -> bool: ...


class Cache(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def clear(self, prefix: str | None = None) -> None: ...


class EventBus(Protocol):
    async def publish(self, topic: str, data: dict) -> None: ...
    async def subscribe(self, topic: str, handler) -> None: ...
    async def unsubscribe(self, topic: str, handler) -> None: ...


class FileStorage(Protocol):
    async def put(self, key: str, content: bytes) -> str: ...
    async def get(self, key: str) -> bytes | None: ...
    async def delete(self, key: str) -> bool: ...
    async def url(self, key: str) -> str: ...
